/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package P3JuanitaAlmacenV3;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BeliardPc
 */
public class MantenedorJAV3 extends javax.swing.JFrame {
  
    /**
     * Creates new form MantenedorJAV3
     */
     ArrayList<Producto> Lista = new ArrayList<>();
    public MantenedorJAV3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BotonBuscar = new javax.swing.JButton();
        TextoBuscar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextoID = new javax.swing.JTextField();
        TextoNombre = new javax.swing.JTextField();
        TextoMarca = new javax.swing.JTextField();
        TextoCategoria = new javax.swing.JTextField();
        TextoCantidad = new javax.swing.JTextField();
        TextoPrecio = new javax.swing.JTextField();
        TextoIDA = new javax.swing.JTextField();
        BotonAgregar = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        BotonEditar = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        tablaproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Marca", "Categoria", "Cantidad", "Precio", "ID Almacen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaproductos);
        if (tablaproductos.getColumnModel().getColumnCount() > 0) {
            tablaproductos.getColumnModel().getColumn(0).setResizable(false);
            tablaproductos.getColumnModel().getColumn(1).setResizable(false);
            tablaproductos.getColumnModel().getColumn(2).setResizable(false);
            tablaproductos.getColumnModel().getColumn(3).setResizable(false);
            tablaproductos.getColumnModel().getColumn(4).setResizable(false);
            tablaproductos.getColumnModel().getColumn(5).setResizable(false);
            tablaproductos.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Categoria:");

        jLabel4.setText("Marca:");

        jLabel5.setText("Cantidad:");

        jLabel6.setText("Precio:");

        jLabel7.setText("ID Almacen:");

        BotonBuscar.setBackground(new java.awt.Color(255, 153, 0));
        BotonBuscar.setText("Buscar");
        BotonBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        TextoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoBuscarActionPerformed(evt);
            }
        });

        jLabel9.setText("Buscar producto por ID:");

        TextoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoIDActionPerformed(evt);
            }
        });

        BotonAgregar.setBackground(new java.awt.Color(153, 255, 153));
        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonBorrar.setBackground(new java.awt.Color(255, 102, 102));
        BotonBorrar.setText("Borrar");
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        BotonEditar.setBackground(new java.awt.Color(255, 255, 102));
        BotonEditar.setText("Editar");
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });

        BotonLimpiar.setBackground(new java.awt.Color(153, 204, 255));
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        jLabel8.setText("Para borrar: ");

        jLabel10.setText("Introdusca la ID seleccionada en");

        jLabel11.setText("la casilla \"Buscar\".");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextoCantidad)
                                            .addComponent(TextoCategoria)
                                            .addComponent(jLabel9)
                                            .addComponent(TextoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(TextoID)
                                            .addComponent(TextoNombre)
                                            .addComponent(TextoMarca)
                                            .addComponent(TextoPrecio)
                                            .addComponent(TextoIDA))))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(BotonAgregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(BotonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonLimpiar)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBuscar)
                    .addComponent(TextoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAgregar)
                    .addComponent(BotonEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonLimpiar)
                    .addComponent(BotonBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(TextoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(TextoIDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoBuscarActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        TextoID.setText("");
        TextoNombre.setText("");
        TextoMarca.setText("");
        TextoCategoria.setText("");        
        TextoCantidad.setText("");
        TextoPrecio.setText("");
        TextoIDA.setText("");
          // TODO add your handling code here:
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
   
        int numElementos=Lista.size();
    int marcador=0;
    if (marcador==0){
    for(int i=0;i<numElementos;i++){
        String temporal=Lista.get(i).getId();
        marcador=0;
        if(temporal.equals(TextoBuscar.getText())){
            TextoID.setText(Lista.get(i).getNombre());
            TextoNombre.setText(Lista.get(i).getNombre());
            TextoMarca.setText(Lista.get(i).getMarca());
            TextoCategoria.setText(Lista.get(i).getCategoria());
            TextoCantidad.setText(Lista.get(i).getCantidad());
            TextoPrecio.setText(Lista.get(i).getPrecio());
            TextoIDA.setText(Lista.get(i).getIdalmacen());
                 
            break;
        }
    marcador=1;
    }

}if(marcador==1){
        JOptionPane.showMessageDialog(null,"Medicamento no existe en la tabla."); 
        TextoID.setText("");
        TextoNombre.setText("");
        TextoMarca.setText("");
        TextoCategoria.setText("");
        TextoCantidad.setText("");
        TextoPrecio.setText("");
        TextoIDA.setText("");
        TextoBuscar.setText("");
        
    }
        
    }//GEN-LAST:event_BotonBuscarActionPerformed

    public void mostrarDatos(){
        String matriz[][]= new String[Lista.size()][7];
            for (int i = 0; i < Lista.size(); i++) {
            matriz [i][0]=Lista.get(i).getId();
            matriz [i][1]=Lista.get(i).getNombre();
            matriz [i][2]=Lista.get(i).getMarca();
            matriz [i][3]=Lista.get(i).getCategoria();
            matriz [i][4]=Lista.get(i).getCantidad();
            matriz [i][5]=Lista.get(i).getPrecio();
            matriz [i][6]=Lista.get(i).getIdalmacen();
            
        }
        tablaproductos.setModel(new javax.swing.table.DefaultTableModel (matriz, new String[]{
        "ID","Nombre","Marca","Categoria","Cantidad","Precio","Id Almacen"}));
        
        
    }
    
    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        int proceder=0;
        int validados=0;
        if((TextoID.getText().length()==0)||(TextoNombre.getText().length()==0)||(TextoMarca.getText().length()==0)||(TextoCategoria.getText().length()==0)||(TextoCantidad.getText().length()==0)||(TextoPrecio.getText().length()==0)||(TextoIDA.getText().length()==0)){
        proceder=0;  
        }else
        proceder=1;
        if(proceder==0){
        
        JOptionPane.showMessageDialog(null,"Campos vacios en formulario, intente nuevamente");
        
        Producto producto = new Producto(
        TextoID.getText(),
        TextoNombre.getText(),
        TextoMarca.getText(),
        TextoCategoria.getText(),
        TextoCantidad.getText(),
        TextoPrecio.getText(),
        TextoIDA.getText());    
        }else{
        Producto producto = new Producto(TextoID.getText(),TextoNombre.getText(),TextoMarca.getText(),TextoCategoria.getText(),TextoCantidad.getText(),TextoPrecio.getText(),TextoIDA.getText());
        Lista.add(producto);
        
        mostrarDatos();
        
        JOptionPane.showMessageDialog(null,"Registro Agregado a tabla exitosamente");
        TextoID.setText("");
        TextoNombre.setText("");
        TextoMarca.setText("");
        TextoCategoria.setText("");
        TextoCantidad.setText("");
        TextoPrecio.setText("");
        TextoIDA.setText("");   // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarActionPerformed
    }
        
    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
    int Elementos=Lista.size(); 
    
    for(int i=0;i<Elementos;i++){
    String temporal=Lista.get(i).getId();
    if(temporal.equals(TextoBuscar.getText())){    
    Lista.remove(i).setCategoria("");
    mostrarDatos();
    JOptionPane.showMessageDialog(null,"El prodcuto "+(TextoBuscar.getText())+", se elimino exitosamente");

  }

  }// TODO add your handling code here:
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
    int Elementos=Lista.size();
    int marcador=0;
    if (marcador==0){   
    for(int i=0;i<Elementos;i++){    
        String temporal=Lista.get(i).getId();
        if(temporal.equals(TextoID.getText())){
            Lista.get(i).setNombre(TextoNombre.getText());
            Lista.get(i).setMarca(TextoMarca.getText());
            Lista.get(i).setCategoria(TextoCategoria.getText());
            Lista.get(i).setCantidad(TextoCantidad.getText());
            Lista.get(i).setPrecio(TextoPrecio.getText());
            Lista.get(i).setIdalmacen(TextoIDA.getText());
            
            marcador=1;  
            break;
        }           
      
    }
    mostrarDatos();
    }
   
    if(marcador==1){
        JOptionPane.showMessageDialog(null,"Producto modificado."); 
        TextoNombre.setText("");
        TextoMarca.setText("");
        TextoCategoria.setText("");
        TextoCantidad.setText("");
        TextoPrecio.setText("");
        TextoIDA.setText("");
        
    }else{
    JOptionPane.showMessageDialog(null,"Producto no registrado."); 
        TextoNombre.setText("");
        TextoMarca.setText("");
        TextoCategoria.setText("");
        TextoCantidad.setText("");
        TextoPrecio.setText("");
        TextoIDA.setText("");
        TextoBuscar.setText("");
}

 
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void TextoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorJAV3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorJAV3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorJAV3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorJAV3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MantenedorJAV3().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JTextField TextoBuscar;
    private javax.swing.JTextField TextoCantidad;
    private javax.swing.JTextField TextoCategoria;
    private javax.swing.JTextField TextoID;
    private javax.swing.JTextField TextoIDA;
    private javax.swing.JTextField TextoMarca;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaproductos;
    // End of variables declaration//GEN-END:variables
}
