/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package P3JuanitaAlmacen;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Usuario
 */
public class MantenedorJuanita extends javax.swing.JFrame {
       
    String ID = "";
    String Nombre = "";
    String Marca = "";
    String Categoria = "";
    String Cantidad = "";
    String Precio = "";
    String IDAlmacen = "";
    ArrayList <Producto> Productos = new ArrayList <>();
    
    
    
    public MantenedorJuanita() {
            initComponents();    
              PantallaTabla.addMouseListener(new MouseAdapter(){
              DefaultTableModel model = new DefaultTableModel();
        
        public void MouseClicked(MouseEvent e){
            int i =PantallaTabla.getSelectedRow();
            ID = (PantallaTabla.getValueAt(i,0).toString());
            Nombre = (PantallaTabla.getValueAt(i, 1).toString());
            Marca = (PantallaTabla.getValueAt(i, 2).toString());
            Categoria = (PantallaTabla.getValueAt(i, 3).toString());
            Precio = (PantallaTabla.getValueAt(i, 4).toString());
            IDAlmacen = (PantallaTabla.getValueAt(i, 5).toString());
        }});
        
        
    } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PantallaBuscar = new javax.swing.JTextField();
        BotonAgregar = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        BotonEditar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        PantallaID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PantallaNombre = new javax.swing.JTextField();
        PantallaMarca = new javax.swing.JTextField();
        PantallaCategoria = new javax.swing.JTextField();
        PantallaCantidad = new javax.swing.JTextField();
        PantallaPrecio = new javax.swing.JTextField();
        PantallaIDAlmacen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PantallaTabla = new javax.swing.JTable();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Interfas: Doña Juanita V3.3 \"La venganza\"");

        jLabel2.setText("ID:");

        PantallaBuscar.setBackground(new java.awt.Color(255, 255, 204));
        PantallaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaBuscarActionPerformed(evt);
            }
        });

        BotonAgregar.setBackground(new java.awt.Color(51, 255, 51));
        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        BotonEditar.setText("Editar");
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });

        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        PantallaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaIDActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre:");

        jLabel4.setText("Marca:");

        jLabel5.setText("Categoria:");

        jLabel6.setText("Cantidad:");

        jLabel7.setText("Precio:");

        jLabel8.setText("Id Almacen:");

        PantallaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaNombreActionPerformed(evt);
            }
        });

        PantallaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaMarcaActionPerformed(evt);
            }
        });

        PantallaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaCategoriaActionPerformed(evt);
            }
        });

        PantallaCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaCantidadActionPerformed(evt);
            }
        });

        PantallaPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaPrecioActionPerformed(evt);
            }
        });

        PantallaIDAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaIDAlmacenActionPerformed(evt);
            }
        });

        PantallaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Marca", "Categoria", "Cantidad", "Precio", "IdAlmacen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(PantallaTabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BotonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BotonEliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BotonAgregar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PantallaID)
                                .addComponent(PantallaNombre)
                                .addComponent(PantallaMarca)
                                .addComponent(PantallaCategoria)
                                .addComponent(PantallaCantidad)
                                .addComponent(PantallaPrecio)
                                .addComponent(PantallaIDAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BotonBuscar)
                            .addGap(18, 18, 18)
                            .addComponent(PantallaBuscar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBuscar)
                    .addComponent(PantallaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PantallaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PantallaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PantallaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PantallaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PantallaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PantallaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(PantallaIDAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEditar)
                    .addComponent(BotonEliminar)
                    .addComponent(BotonAgregar))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        PantallaBuscar.setText("");
        PantallaID.setText("");
        PantallaNombre.setText("");
        PantallaMarca.setText("");
        PantallaCategoria.setText("");
        PantallaCantidad.setText("");
        PantallaPrecio.setText("");
        PantallaIDAlmacen.setText("");
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < Productos.size(); i++) {
            if(ID.equals(Productos.get(i).getId())){
               Productos.remove(i);
               
            }
            
        }
        mostrarDatos();
        
        
        
    }//GEN-LAST:event_BotonEliminarActionPerformed
  
    
    
    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        // TODO add your handling code here:
      
        Producto producto = new Producto(
        PantallaID.getText(),
        PantallaNombre.getText(),
        PantallaMarca.getText(),
        PantallaCategoria.getText(),
        PantallaCantidad.getText(),
        PantallaPrecio.getText(),
        PantallaIDAlmacen.getText());
        
        Productos.add(producto);
        
        mostrarDatos();
        PantallaID.setText("");
        PantallaNombre.setText("");
        PantallaMarca.setText("");
        PantallaCategoria.setText("");
        PantallaCantidad.setText("");
        PantallaPrecio.setText("");
        PantallaIDAlmacen.setText("");
        
      
            
        /*for (int i = 0; i < Productos.size(); i++) {
        System.out.println(Productos.get(i).getNombre());    
        }
        System.out.println("====");*/
        
    }//GEN-LAST:event_BotonAgregarActionPerformed
    public void mostrarDatos(){
        String matriz[][]= new String[Productos.size()][7];
            for (int i = 0; i < Productos.size(); i++) {
            matriz [i][0]=Productos.get(i).getId();
            matriz [i][1]=Productos.get(i).getNombre();
            matriz [i][2]=Productos.get(i).getMarca();
            matriz [i][3]=Productos.get(i).getCategoria();
            matriz [i][4]=Productos.get(i).getCantidad();
            matriz [i][5]=Productos.get(i).getPrecio();
            matriz [i][6]=Productos.get(i).getIdalmacen();
            
        }
        PantallaTabla.setModel(new javax.swing.table.DefaultTableModel (matriz, new String[]{
        "ID","Nombre","Marca","Categoria","Cantidad","Precio","Idalmacen"}));
        
        
    }
    
    
    
    private void PantallaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaBuscarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_PantallaBuscarActionPerformed

    private void PantallaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaIDActionPerformed

    private void PantallaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaNombreActionPerformed

    private void PantallaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaMarcaActionPerformed

    private void PantallaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaCategoriaActionPerformed

    private void PantallaCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaCantidadActionPerformed

    private void PantallaPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaPrecioActionPerformed

    private void PantallaIDAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaIDAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaIDAlmacenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorJuanita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorJuanita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorJuanita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorJuanita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorJuanita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JTextField PantallaBuscar;
    private javax.swing.JTextField PantallaCantidad;
    private javax.swing.JTextField PantallaCategoria;
    private javax.swing.JTextField PantallaID;
    private javax.swing.JTextField PantallaIDAlmacen;
    private javax.swing.JTextField PantallaMarca;
    private javax.swing.JTextField PantallaNombre;
    private javax.swing.JTextField PantallaPrecio;
    private javax.swing.JTable PantallaTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
